version: '3'

tasks:
  docker-clean:
    cmds:
      - docker image prune --all --force
      - docker system prune --all --force

  docker-debug:
    cmds:
      - docker exec -it home-lab-control-plane bash

  cluster-create:
    cmds:
      - kind create cluster --config single-node-extra-port-mapping.yaml --name home-lab
    dir: code

  cluster-status:
    cmds:
      - kind get clusters
      - kubectl get nodes -o wide
    dir: code

  cluster-delete:
    cmds:
      - kind delete cluster --name home-lab
    dir: code

  cluster-ingress-setup:
    cmds:
      - kubectl label node home-lab-control-plane ingress-ready=true
      - kubectl apply -f ingress-nginx.yaml
      - openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/CN=nginxsvc/O=nginxsvc"
      - kubectl -n ingress-nginx create secret tls tls-secret --key tls.key --cert tls.crt || true
      - "kubectl wait --namespace ingress-nginx \
        --for=condition=ready pod \
        --selector=app.kubernetes.io/component=controller \
        --timeout=90s"
      - kubectl -n ingress-nginx get services
    dir: code

  dashboard-setup:
    cmds:
      - helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
      - helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard
      - kubectl apply -f admin-user.yaml
      - kubectl -n kubernetes-dashboard create token admin-user
      - "kubectl wait --namespace kubernetes-dashboard \
        --for=condition=ready pod \
        --selector=app=kubernetes-dashboard-kong \
        --timeout=90s"
      - kubectl -n kubernetes-dashboard port-forward svc/kubernetes-dashboard-kong-proxy 8443:443
    dir: code

  dashboard-access:
    cmds:
      - kubectl -n kubernetes-dashboard create token admin-user
      - open https://localhost:8443
    dir: code

  cloud-provider-setup:
    cmds:
      - VERSION="$(basename $(curl -s -L -o /dev/null -w '%{url_effective}' https://github.com/kubernetes-sigs/cloud-provider-kind/releases/latest))" && docker run -d --name cloud-provider-kind --rm --network host -v /var/run/docker.sock:/var/run/docker.sock registry.k8s.io/cloud-provider-kind/cloud-controller-manager:${VERSION}
    dir: code

  cloud-provider-check:
    cmds:
      - docker ps --filter name=cloud-provider-kind
      # - docker logs cloud-provider-kind
    dir: code

  cloud-provider-delete:
    cmds:
      - docker stop cloud-provider-kind || true
      - docker stop kind-gateway-proxy || true
      - docker rm kind-gateway-proxy || true
    dir: code

  cluster-gateway-setup:
    cmds:
      - kubectl apply -f gateway-infra.yaml
    dir: code

  cluster-gateway-check:
    cmds:
      - kubectl get gateway -n gateway-infra gateway
    dir: code

  istio-setup:
    cmds:
      - helm repo add istio https://istio-release.storage.googleapis.com/charts
      - helm repo update
      - helm install istio-base istio/base -n istio-system --set defaultRevision=default --create-namespace
      - helm install istiod istio/istiod -n istio-system --wait
    dir: code

  istio-check:
    cmds:
      - helm ls -n istio-system
      - helm status istiod -n istio-system
      - kubectl get deployments -n istio-system --output wide
    dir: code

  app-podinfo-create:
    cmds:
      - kubectl apply -f app-podinfo.yaml
    dir: code

  app-podinfo-port-forward:
    cmds:
      - kubectl port-forward svc/podinfo 9898:9898
    dir: code

  app-podinfo-delete:
    cmds:
      - kubectl delete -f app-podinfo.yaml
    dir: code

  app-podinfo-check:
    cmds:
      - "curl -kiv https://podinfo.example.com"
      - "curl -H 'Host: podinfo.example.com' localhost"

  app-echo-create:
    cmds:
      - kubectl apply -f app-echo.yaml
    dir: code

  app-echo-port-forward:
    cmds:
      - kubectl port-forward svc/echo 3000:3000 -n demo
    dir: code

  app-echo-check:
    cmds:
      - "docker run -d --name kind-gateway-proxy \
          --network kind \
          -p 8080:80 \
          alpine/socat \
          TCP-LISTEN:80,fork TCP:172.18.0.3:80 || true"
      - "curl -H 'Host: echo.example.gateway.kind.com' http://localhost:8080"
    dir: code

  app-echo-debug:
    cmds:
      - kubectl get gateway -n gateway-infra gateway -o yaml
      - kubectl get httproute -n demo echo -o yaml
      - docker logs -f cloud-provider-kind
    dir: code

  k9s:
    cmds:
      - k9s
